apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/organizations.services.k8s.aws_organizations.yaml
  - bases/organizations.services.k8s.aws_organizationalunits.yaml
