apiVersion: v1
name: organizations-chart
description: A Helm chart for the ACK service controller for AWS Organizations (Organizations)
version: 1.0.5
appVersion: 1.0.5
home: https://github.com/aws-controllers-k8s/organizations-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/organizations-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Organizations Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/organizations-maintainer
keywords:
  - aws
  - kubernetes
  - organizations
